export { default as Home } from './Home.jsx'
export { default as Login } from './Login.jsx'
export { default as Signup } from './Signup.jsx'
export { default as Events } from './Events.jsx'
export { default as About } from './About.jsx'